### ISSUE TITLE
[Module 2] Narrative 'saving lives' image changes

### ISSUE THREAD

**Issue by bcave** [theodi/ODI-eLearning#10]
Please change image on this slide to a still taken from 0:06 of this video: https://vimeo.com/9182869

Please also link to video in slide text

**Comment by aaronpont** [comment]
Agree.

Developers:
I have picked out the moment that the concentric circles are at their most intense and the right size
Please replace current image with this still -
![image](https://cloud.githubusercontent.com/assets/12693190/7933511/771b4684-0917-11e5-88cf-607b76d66208.png)

Change text on page 6a as per attached to reflect the change -
![image](https://cloud.githubusercontent.com/assets/12693190/7933588/1340c160-0918-11e5-88f7-c66255a231f4.png)
Thanks,
aAron

**Comment by aaronpont** [comment]
PS, the line of text that says "Show me the Haiti Open Street Map" should be a hyperlink to the open map.
Thanks,
aAron

**Comment by jasonbutler** [comment]
Picture replaced - and also replaced in the corresponding question.
Link to http://hotosm.org/projects/haiti-2 added  - Haiti Open Streetmap
Link added to resources drawer

**Comment by davetaz** [comment]
closed by ea58578b9cdbe35a1022cf4d72058363f93ae0dc
