### ISSUE TITLE
[Module 2] Quiz question 1 change text

### ISSUE THREAD

**Issue by bcave** [theodi/ODI-eLearning#11]
Add capitalised text to question: Open data is driving innovation and growth IN THE PRIVATE SECTOR by:

**Comment by aaronpont** [comment]
Yes, please change.
aAron

**Comment by jasonbutler** [comment]
Text updated

**Comment by davetaz** [comment]
@jasonbutler I think what @bcave meant was to add the text but not to capitalise it. Can we have it in lower case please. Remember to close the issue with a "Fixes #x" where x is 11. I can't type it as it will close the issue. Thanks

**Comment by aaronpont** [comment]
Agreed.
aAron
