### ISSUE TITLE
[Module 7] Video 7 - first answer is odd - cut?

### ISSUE THREAD

**Issue by AnnaDouglasScott** [theodi/ODI-eLearning#110]
Ulrich's first answer is weird: "Well by sustainable open data we mean at its core to answer the question how long will the data be around" - though I'm not sure there's anything we can do about that, unless it can be cut so Ulrich goes straight in to say: "We can think of two main factors that affect the sustainability..."

**Comment by aaronpont** [comment]
Hello,
Short answer: leave it alone, its fine!
Long answer… :)
I have reviewed the video, and I agree with what you found.
I suggest that we don't doctor it, though, but leave it alone.  It is the best take with the best 'feel'.  If we cut it up, it will look like we cut it up, and that will take away from the casual nature of the ‘feel’ of the video.
From a learner perspective, the issues will wash over them.  Key messages still resonate throughout.
When they return for a second viewing, they will notice it is 'a bit out', but it still won't kill them.
The intention of the video is to provide the learner with a human connection to the elearning.  It will confirm with them that Open Data is a people led organisation, that there are experts who want to tell you all about open data, that they are no different from you.  The connection is more important than the content.
The content the expert is talking about is reflected in the content of the rest of the course, but said in different words.  That is why we spent so much time getting the messages right in the video scripts, to ensure that key messages are stated clearly and with enthusiasm and confidence.
And, as we all found, what we say on video is sometimes different from the script, but that makes it more meaningful for the learner.  They trust the expert when the expert is human.  Once we have the trust of the learner, they are significantly more open to ‘absorbing’ the content following.
Don’t forget, we are looking at this several times, learners won’t.  And learners are more forgiving than we think!
What'cha think?
Thanks,
aAron
