### ISSUE TITLE
[Module 2] quiz question 2 text change

### ISSUE THREAD

**Issue by bcave** [theodi/ODI-eLearning#12]
Please remove question marks from answers 2 & 3

**Comment by aaronpont** [comment]
see this response
[All Modules] Question Marks in quiz answers Adapt All modules

**Comment by jasonbutler** [comment]
? replaced with full stop as per correct answer for consistency

**Comment by davetaz** [comment]
closed by ea58578b9cdbe35a1022cf4d72058363f93ae0dc
