### ISSUE TITLE
Module 3 - text correction

### ISSUE THREAD

**Issue by aaronpont** [theodi/ODI-eLearning#135]
Hello,
As you can see below, this bit of text slipped through the net.  Could ODI have a look at it and suggest suitable wording?
Thanks,
aAron

![image](https://cloud.githubusercontent.com/assets/12693190/8156043/d0056ef8-1341-11e5-9e99-77691952a73a.png)

**Comment by davetaz** [comment]
We have done the internal review on our text and will be updating it over the coming week, so got it covered!
