### ISSUE TITLE
[All Modules] Question Marks in quiz answers

### ISSUE THREAD

**Issue by bcave** [theodi/ODI-eLearning#14]
Please remove inconsistent question marks from question answers (either all answers should have them or none should)

**Comment by aaronpont** [comment]
The use of question marks on incorrect answers and the use of a full stop on correct answers is a device used to lead learners to remember key messages or to confirm correct attitudes and behaviours.
When you read an answer with a question mark, you are left wondering, and very quickly dismiss it as an option.
When you read the answer with the full stop, it resonates as a clear and affirming statement, which satisfies the learners need for agreement and confirmation of their understanding.
It is a neat psychological method to lead learners to adopt your key message.
As I said in my other feedback, one of our developers cottoned on to it and agreed that it worked as he now is able to recite most key concepts on the modules he is working on.
Short answer.... yadda yadda yadda... :)
But I agree, we will go through all modules and make sure they are consistent.
aAron

**Comment by davetaz** [comment]
Would love the reference for this one @aaronpont, was there a statistically significant study done? All I can see is our community asking why there is a question mark on the end of phrase which is not a question.

**Comment by aaronpont** [comment]
OK, lets strip them out!  
I don't have access to the evaluations we did in Australia on assessment practices, and I won't have time to badger my colleagues for it! :)
If it is going to raise eyebrows, lets strip them out.  I would rather raise smiles than eyebrows! :)
I will add this as an action in the All modules category.
(btw, it is edgy, but very effective).
Thanks,
aAron
