### ISSUE TITLE
[All Modules] Block colour changes

### ISSUE THREAD

**Issue by bcave** [theodi/ODI-eLearning#15]
The 'are you ready' blocks is in a faded grey with a white one next. Please change the 'are you ready block' to white, the following block to yellow to match burst image and them adjust further blocks to run white/colour/white/colour.

**Comment by aaronpont** [comment]
There are two reasons for the choice of colours for the 'are you ready' section.

First, there needs to be a logical break between content and formative activities for the learner.  We needed it to be obvious, so we chose a simple grey to delineate the difference, and the text 'are you ready...' clearly indicates the learning is over, and knowledge checking is about to start.

Second, stylistically, there are quite a lot of images with a white background that sit on a white page.  We deliberately chose those images to suit the white background, which makes viewing on all devices easy on the eye.  If we land these images on a coloured background, they will lose their impact.
Changing the colour sequences will upset a lot of the styling that we have worked on.  It won't kill anyone, but the style we have created is very easy on the eye and resonates the mood and intent of the content.
Would you mind terribly if we left it as is?
Thanks,
aAron

**Comment by davetaz** [comment]
![screenshot from 2015-06-02 17 47 20](https://cloud.githubusercontent.com/assets/180099/7941494/989d9db0-094f-11e5-822f-5922d40daa41.png)

> First, there needs to be a logical break between content and formative activities for the learner

I agree completely and this needs to be consistent across the modules. We think 4 is great. It works really well. In 2 it doesn't. I can't tell the difference in colours between the "Are you ready block" and the first question block and this is a problem. There needs to be a divide here. Also the yellow in the splat links me to the thing before, not the thing after. 

I understand the some images look better on white argument, however this cannot compromise the flow. I've inverted the whole lot in my copy and it looks much better (see image).

**Comment by aaronpont** [comment]
I agree, white leading to white does not work.
Developers, can we ensure that all modules avoid this?
I suspect we tripped over module 2 somehow, as I believe all the others have consistent colour sequencing.
Thanks,
aAron
