### ISSUE TITLE
[Module 2] First question

### ISSUE THREAD

**Issue by AnnaDouglasScott** [theodi/ODI-eLearning#16]
Change "What benefits does open data literacy provide to private sector?" to "How can open data literacy benefit the private sector?"

**Comment by aaronpont** [comment]
I don't see this question in the version that I am working from:
http://reviewarea.co.uk/Secure/odi/module2/v1/#/id/co-01

Which version of the module are you referencing?
Thanks,
aAron

**Comment by danscholes** [comment]
I think it's in the video...

**Comment by aaronpont** [comment]
Doh! Sorry, yes, please change!
Thanks,
aAron
