### ISSUE TITLE
[Module 4] Change background of video block in adapt to match video

### ISSUE THREAD

**Issue by davetaz** [theodi/ODI-eLearning#2]
The two blues clash, thus would it look better with the same background  (to the same scale if possible) as used in the video

**Comment by aaronpont** [comment]
Yes, agree. Dev, please action.

**Comment by danscholes** [comment]
Hi all, I agree with the idea of matching colours. However as the branding on the videos isn't signed off yet, it would be a good idea to hold fire on this one for now as there could be a clash if the titles in the videos change again. Once we have approval on the videos - we can action the block colour change to match.

Dev - No action to be taken yet.

**Comment by davetaz** [comment]
Fine with me. As you say the video changes might make this change redundant. Just a heads up for later.
