### ISSUE TITLE
[Module 4] - change question 3

### ISSUE THREAD

**Issue by AnnaDouglasScott** [theodi/ODI-eLearning#21]
Change "Describe how open data licencing should be provided for, in the tender, procurement and contracting lifecycle?" to "How can open data licensing be provided for in tenders, procurement and contracting?"

**Comment by aaronpont** [comment]
Agreed.  I have changed the question and formulated an appropriate correct response, which can be nudged in the next review if required.
Developers, I have updated the changes in Module 4, page 7i, 7k and 7L in the wire frame.
Thanks,
aAron
