### ISSUE TITLE
CKAN can be a data management platform

### ISSUE THREAD

**Issue by JeniT** [theodi/ODI-eLearning#298]
It's not just a data catalog as this module implies.

**Comment by davetaz** [comment]
would be closed by #299

**Comment by JeniT** [comment]
I don't think it would. I fixed a grammatical issue in the description of data catalogs, but I didn't add a CKAN reference into the data management section.

**Comment by davetaz** [comment]
would it be OK to say that CKAN has simple data management functionality compared to that of other platforms such as Socrata. This means that CKAN is less strict with the data that it lets you import and thus reduces the amount of effort and technical knowledge required. 
?

**Comment by JeniT** [comment]
Something like that sounds accurate to me, though I haven't played around with either platform lately, I just know that CKAN can host now.

**Comment by davetaz** [comment]
Host yes. Manipulate and change data, define schema and export in different formats no, these were the main differences I was trying to emphasise here.

**Comment by JeniT** [comment]
ok
