### ISSUE TITLE
Open & popular formats for data, particularly geospatial data

### ISSUE THREAD

**Issue by JeniT** [theodi/ODI-eLearning#301]
I think that module 9 would be improved if it could include a mention of some additional choices that people have to make, particularly around vocabularies. For example, I'd expected some mention of:
- using open standards & open vocabularies, perhaps pointing to schema.org
- using popular standards for geospatial data, such as GeoJSON or Shape files
- using structured document formats such as HTML or XML as well as (CSV) metadata for things like contracts

Is there scope for adding some of this?

**Comment by davetaz** [comment]
There is scope for adding a block on above the "Are your formats in order" on geospatial data. This would relate nicely back to the hierarchical discussion. We could also include GeoJSON and KML standard as examples of specific formats based upon the JSON and XML formats respectively.

Vocabularies would add a few too many messages to this module. 

Would that be OK?

**Comment by JeniT** [comment]
sounds good
