### ISSUE TITLE
"Discover insights" in "What are the benefits of cleaning data?" doesn't make sense

### ISSUE THREAD

**Issue by JeniT** [theodi/ODI-eLearning#303]
This currently says:

> Many data cleaning tools, including Open Refine help you to combine and enrich datasets.
> 
> Without a clean dataset, this process will not be useful to you.
> 
> Careful preparation is essential to the success of any data-driven project.

These sentences don't seem to relate well to each other or the title of the topic. What should it be saying?

**Comment by davetaz** [comment]
I'll be honest. I have absolutely no idea. 

I wonder what the original script said and how many changes it has already been through?
