### ISSUE TITLE
"Using the 4th star" section is confusing

### ISSUE THREAD

**Issue by JeniT** [theodi/ODI-eLearning#307]
(httpRange14 alert!) The text says:

> This identifier is for the physical thing itself. An ISBN references a physical book but requires further context to allow a user to locate the object using it, a web based identifier for the book also references the book and not a web page about the book but adds the context needed for any human or machine to use it without additional support.
> 
> The web-based identifier also gives machines the context they need to make sense of the identifier. Consider a 3D printer. Using a web based identifier, the 3D printer could, in theory, get all the data needed to print the physical thing.

The use of an ISBN as an example is a confusing one because an ISBN does _not_ identify a single physical item (a copy of a book), it identifies an edition of a book. The 3D printer example is also confusing: an identifier that references a pattern for printing something doesn't refer to the copy that you make, but the pattern itself.

I'm not sure exactly what point this section is trying to make, but I don't think it's making it effectively with these examples. Perhaps it would be helpful to use an example where copies of things aren't relevant. For example, the identifier of a postcode area, or the UPRN for a property, or the number of a road, or a school.

**Comment by davetaz** [comment]
I was trying to keep this to something that people use and know exists as an identifier already. Fair point that a Book isn't quiet the right example. Can we put that an ISBN refers to an edition of a book though? 

I  was trying to stay away from identifiers of things that there cannot be exact copies of. I still have the same book as someone else if I own a physical copy of the same edition. "I have that CD" is different from "I have that album".

**Comment by JeniT** [comment]
What's the main thing that you want people to learn from this section? That you can use URLs for physical things? What about using a company number example with OpenCorporates? Or the DBPedia version of One Direction?

**Comment by JeniT** [comment]
[separate comment: update all references to One Direction to Taylor Swift]

**Comment by davetaz** [comment]
+1m on that :)

**Comment by davetaz** [comment]
I think the company number would work well and also link to the permID work, will look into it.
