### ISSUE TITLE
Email entry for cloud sync has title "index.html"

### ISSUE THREAD

**Issue by Floppy** [theodi/ODI-eLearning#316]
Tiny thing, just looks a bit shonky.

![img_2943](https://cloud.githubusercontent.com/assets/3565/10452460/158f5bdc-719d-11e5-92b5-0d3dd2d3c8d7.jpg)

**Comment by davetaz** [comment]
Agree, no sure how you change it without complicated libraries. I might move this to the front screen and say "enter email to get started"

**Comment by davetaz** [comment]
Solved with new message box
