### ISSUE TITLE
Progress bar inconsistencies

### ISSUE THREAD

**Issue by Floppy** [theodi/ODI-eLearning#317]
I've completed the first lesson, and synced the data. However, when I go back in, the progress bar isn't 100% full, no matter whether I finish by going to the menu or the next module. I may have missed something, but I can't find it...

![img_2945](https://cloud.githubusercontent.com/assets/3565/10452482/31841a62-719d-11e5-89da-df9c9a507c48.jpg)

Also, when I go into the main menu, the progress bar is completely different on the first lesson

![img_2944](https://cloud.githubusercontent.com/assets/3565/10452485/34b85d38-719d-11e5-95a9-dcf6cc71aea5.jpg)

This is the case even going back this morning 12 hours after completing the lesson.

**Comment by davetaz** [comment]
Will look into this in the data endpoint and see what I can find. Thanks :)

**Comment by davetaz** [comment]
Module 1 Last Saved: "Tue Oct 13 2015 11:28:03 GMT+0100 (BST)",
Module 1 Completion:{\"completion\":\"111111100000\",\"_isCourseComplete\":false,\"_isAssessmentPassed\":true}}"

Interesting... Looks like it forgets you have done the questions.

**Comment by davetaz** [comment]
Could not reproduce

**Comment by davetaz** [comment]
Confirmed as issue
