### ISSUE TITLE
Module 8 typo and broken link

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/ODI-eLearning#319]
Hi @davetaz 
Firstly, thanks for the great resource I found at http://www.europeandataportal.eu/elearning/en/
I hope this is the right place to report issues.

"Geting to grips with platforms" is mis-spelt; it should be "Getting".

Also the link to https://how-to.usopendata.org/basics/data-repositories.html in Open data platform design approaches, returns an error.

Sorry about originally posting this in the wrong repository - https://github.com/theodi/EUeLearning/issues/1

**Comment by davetaz** [comment]
Both files updated
