### ISSUE TITLE
Picture edits 

### ISSUE THREAD

**Issue by steffica72** [theodi/ODI-eLearning#321]
Module 1. Block: 'Why do we need open data'
First picture (transforming government). Change to drawing rather than photograph. 
Third picture (protecting our planet). 

Module 4. Block: 'Types of licenses'. 
Change picture of stone and sky. 
Appear again in 'Licenses and third parties' part of quiz - last question. 

Module 7. Block 'Making sense of sustainability in open data' 
Third picture: 'wide reuse of open data'. 
Appears again in quiz, 'What influences sustainability?' (answer: 'wide reuse')

Module 11. Block 'What are the benefits of cleaning data?' 
Third picture 'Discover insights' (picture of diamonds). Although this fits with the theme, it is incongruent with the other pictures in the scrolling box. 

Module 11. Black summary box at the end, 'Get started with data cleaning in Open Refine<./a>' 
Remove the full stop to hide code.

**Comment by davetaz** [comment]
Split into issues #324 #325 #326 #327 and #328
