### ISSUE TITLE
'Learn More' description 

### ISSUE THREAD

**Issue by steffica72** [theodi/ODI-eLearning#330]
Content needs to be put here. 
Suggest: "If you are enjoying our e-Learning programme and want to take your learning further, why not check out the open data training courses we have on offer. Visit our courses page, or email training@theodi.org to find out more." 
@bcave ^

**Comment by davetaz** [comment]
recommend that is should be a bit more generic.

If you are enjoying our e-Learning programme and want to take your learning further, why not check out the full suite of training on offer from the Open Data Institute. You can also contact us by email at training@theodi.org.

**Comment by steffica72** [comment]
Fair enough, but we still need to point them somewhere. At the moment, the courses page is the best place.
