### ISSUE TITLE
[Module 3] final slide

### ISSUE THREAD

**Issue by AnnaDouglasScott** [theodi/ODI-eLearning#39]
Change "What are the roles of supply and demand in open data initiatives?" to "Demand and supply: how those who produce open data can also use it"

**Comment by danscholes** [comment]
Please can you specify if changes are module based or video based please? Many thanks

**Comment by AnnaDouglasScott** [comment]
Sorry, all I've stated 'module 1,2,3..' meaning 'video 1,2,3..'
