### ISSUE TITLE
Change image for question 4 to be same as on page 6a

### ISSUE THREAD

**Issue by aaronpont** [theodi/ODI-eLearning#40]
Developers,
please change image on question 4 to be the same as the earthquake image on page 6a, as per earlier issue.
Thanks,
aAron

**Comment by jasonbutler** [comment]
Images are already the same?

**Comment by aaronpont** [comment]
The wire frame had a different image.  All good, thanks,
aAron

**Comment by davetaz** [comment]
Fixed by ea58578b9cdbe35a1022cf4d72058363f93ae0dc
