### ISSUE TITLE
EDP edits 

### ISSUE THREAD

**Issue by steffica72** [theodi/ODI-eLearning#436]
http://www.europeandataportal.eu/elearning/en/module8/#/id/co-01
Typo in the page title: "Geting to grips..." > it should be "Getting to grips"
Under "Key features of open data platforms"

> http://www.data.gov.bf/ (which redirects to http://www.data.gov.br) is not working
> Under "Open data platform design approaches"
> 
> Data catalogs:
> 
> > "Take me to Amsterdam CKAN portal", www.amsterdamopendata.nl/home (address should be changed to http://data.amsterdam.nl)
> 
> Comparison
> 
> > "Take me to comparative analysis of data platforms", https://how-to.usopendata.org/basics/data-repositories.html (address should be changed to https://how-to.usopendata.org/en/latest/The-Basics-of-Open-Data/Data-Repositories/)

A user has found some broken links in the following page from e-learning module : http://www.europeandataportal.eu/elearning/en/module4/#/id/co-01

Benefits of open data licensing section :
Providing Clarity  (2nd slide), http://www.opendatamonitor.eu/frontend/web/index.php?r=datacatalogue%2Findex
the link is broken, error message : "Missing required parameters: id"

Simple licences, easily found section :
Singapore Government (2nd slider), http://data.gov.sg/Metadata/OneMapMetadata.aspx?id=DENGUE_CLUSTER&t=SPATIAL
the link is broken : Error 404

Types of licences section :
In Open government licences
Take me to the French Government open licence, http://wiki.data.gouv.fr/wiki/Licence_Ouverte_/_Open_Licence  
the link should lead to http://wiki.data.gouv.fr/wiki/Licence_Ouverte_/_Open_Licence  but it redirects to http://www.data.gouv.fr/fr/faq/

**Comment by davetaz** [comment]
Make new individual issues
