### ISSUE TITLE
EDP fix: Open Gov fix

### ISSUE THREAD

**Issue by steffica72** [theodi/ODI-eLearning#451]
In Open government licences
Take me to the French Government open licence, http://wiki.data.gouv.fr/wiki/Licence_Ouverte_/_Open_Licence  
the link should lead to http://wiki.data.gouv.fr/wiki/Licence_Ouverte_/_Open_Licence  but it redirects to http://www.data.gouv.fr/fr/faq/
http://www.europeandataportal.eu/elearning/en/module8/#/id/co-01

**Comment by davetaz** [comment]
duplicate of #439
