### ISSUE TITLE
[Module 4] Quiz question 3 change text

### ISSUE THREAD

**Issue by bcave** [theodi/ODI-eLearning#5]
Change text to 'find what kind of licence the following dataset is released under: http://data.gov.uk/dataset/monthly-land-registry-property-transaction-data'. Keep answers to the question the same.

**Comment by aaronpont** [comment]
This type of activity works best as part of a deeper dive activity for a topic.  At this stage, it will feel like a structured learning activity which is in contrast to the rest of the programme.  Definitely do this type of activity for subsequent learning activities after learners have completed the introductory modules.
Short answer - messages, attitudes and beliefs. Long answer - you know the drill! :).
Would you mind if we kept this question as is?
Thanks,
aAron

**Comment by davetaz** [comment]
We have a number of these coming up in the later modules which we cannot avoid as they are much more hands on technical module that must have examples. I'm looking for a way to get people used to exploring outside of the safe learning environment and coming back. 

Maybe we could ask "What licence we would expect government expenditure in the UK to be published under?" and have a take me to the dataset to show the evidence? Surely that's ok?

**Comment by aaronpont** [comment]
It would be a great idea to demonstrate to learners how to find a licence in a dataset and identify what type of licence it is to enhance the impact of that question.

The example of the land registry is a good one for a simple to find and understand licence (right there at the top).
Do you have another example site with a little more difficult to find licence, maybe at the bottom of the page, or one that has a link to licences?

We can have a supporting image that graphically indicates where the licence object resides for the particular example.  For example, a graphic of a web page with a big fat arrow pointing to where the licence information resides.
Providing learners with a clear guide on "how to find a licence" is really helpful.  And the reinforcement of a preferred location of a licence and type of licence, such as the land registry example is a good idea, both for publishers and users.

Use supporting text statements like "Best practice suggests placing licence information at the beginning or head of the web page, clearly stating the type of licence.  Provide users with a hyperlink to the body of the licence for easy access." or words to that effect.

This is a great way to build up the activities, from simple to more complex over the upcoming modules.

I can turn that into a short learning activity in the narration.  Then we can add the question to the assessment area -
"Which licence would best suit government expenditure published in the UK?" with the corresponding graphic.
Thanks,
aAron

**Comment by davetaz** [comment]
Agree here, so we add another narrative "Making simple licences easy to find" with UK gov (http://data.gov.uk/dataset/financial-transactions-data-fco) which is easy to find and Singapore gov (http://data.gov.sg/Metadata/OneMapMetadata.aspx?id=DENGUE_CLUSTER&t=SPATIAL) which is less easy (you can either get at it by clicking on the data download or via the terms and conditions link at the bottom of the page. Then we can add the question.

**Comment by aaronpont** [comment]
Agree,
Developers, I will mockup the narration pages and post here, likely today.
Thanks,
aAron

**Comment by aaronpont** [comment]
Developers, 
We will have to create one txt/image page and one two page narrative as there is little scope for including this activity in other sections.  Wait for Dave to confirm content before building.

Dave, can you review the suggested text and clean it up?

The txt/image page introduces the background and the upcoming activity (insert at page 5) 
![image](https://cloud.githubusercontent.com/assets/12693190/7958349/63f76748-09e6-11e5-9b0a-b4e7544e66db.png)

Followed by the two page narrative -
![image](https://cloud.githubusercontent.com/assets/12693190/7958402/cc4a2b96-09e6-11e5-99cf-1f2ff2216cee.png)

![image](https://cloud.githubusercontent.com/assets/12693190/7958407/dc56c1ca-09e6-11e5-8537-fa6b46f6b125.png)

And then change the question for question 3 -
![image](https://cloud.githubusercontent.com/assets/12693190/7958451/767b04d2-09e7-11e5-9883-7550742e06c8.png)

Thanks,
aAron

**Comment by davetaz** [comment]
Looks good to me, the arrows will need to be consistent in style and colour. The text we can give minor updates to once committed. The question also looks fine.

**Comment by aaronpont** [comment]
Thanks,
Developers, please commit these changes.
Designers will make much nicer arrows than PowerPoint ever will! :)
Thanks,
aAron

**Comment by danscholes** [comment]
aAron do we have links for the screengrabs you've used here? The designers will probably want to take their own grabs. Could they go in the wireframes? 

Also, the action - 'And then change the question for question 3' - if we use Q3 here, whats going in place of Q3?

Many thanks

**Comment by aaronpont** [comment]
The URLs are in the hyperlinks in the wireframes -
file:///\\SPONGE-DC\Office\Client%20Files\Open%20Data%20Institute\Open%20Data%20elearning%20suite\Ready%20storyboards%20for%20des&dev\ODI_Module%204_Simplifying_open_data_licences_v1.pptx


Question 3, just change the current text in question 3 for what is displayed on the wireframe.
Ahem, not sure how else to say it? :)  Developers, just grab me if it does not make sense.
Thanks,
aAron

**Comment by aaronpont** [comment]
Developers,
Oh, look at that, I just broke one of the biggest security rules on the planet... don't print out long resource identifiers!  Deleted, sorry!
The wireframes in 'ready storyboards' in client files has the URLs for the screen grabs.
As for question 3, just change the current text for the text in the wireframe.
Grab me if that don't make sense!
Thanks,
aAron

**Comment by danscholes** [comment]
New blocks added, new images included.
