### ISSUE TITLE
Under the OPEN DATA menu, remove the images and decrease the contents by leaving the major info. 

### ISSUE THREAD

**Issue by steffica72** [theodi/ODI-eLearning#540]
For example: Remove the down arrow images, submenu 3 (just use Open data certificate and remove the rest of the words), submenu 4 (just use Open Licence), and remove the rest, etc.

**Comment by steffica72** [comment]
@davetaz  Suggestion: Crunch down the fist 4 things in the menu by removing images/text where necessary, and putting in the other information in a publicly available Google doc which we will point to in the dropdown.

**Comment by davetaz** [comment]
Closed by b9eeeea54702f0b25a209129fa14724f6c40bc36
