### ISSUE TITLE
[Module 7] Third question has 2+ responses

### ISSUE THREAD

**Issue by davetaz** [theodi/ODI-eLearning#62]
02:06 is a repeat of the answer, I think the first cut is better but don't know what the notes on the day said. Either way it is all over the place!!! Horrid.

**Comment by davetaz** [comment]
Not rectified, now the second answer is better

**Comment by danscholes** [comment]
Hi Dave, Can I just confirm - if we were to cut out from 1:49 to 2:01, this would rectify the issue?
Just want to make sure we understand fully this time. 

Many Thanks

**Comment by davetaz** [comment]
Cut from after the question (1m43 in my version) to the second answer start (2m02 in my version). Hope this works in the edit. Although Ulrich "ums" in the second version it is slower and I think clearer as a result of including examples.

**Comment by aaronpont** [comment]
Yes, I was not sure if that preamble was necessary.
I agree, cut from 1:43 to 2:02.
Thanks,
aAron

**Comment by danscholes** [comment]
Great, thanks for clarifying Dave (& aAron). We'll check it works well.
