### ISSUE TITLE
[All images] Need to know the source

### ISSUE THREAD

**Issue by davetaz** [theodi/ODI-eLearning#8]
We need to know the sources so we can ensure that any licenses are abided by. For example the fix me street image in module 2 needs attribution to ordnance survey and possibly fix my street themselves. 

If the images require attribution can these please be added. 

This may be different from other work as that remains private. All our work is public.

**Comment by davetaz** [comment]
Can this data be added to the components.json for each external thing (image, video etc) as "source", "credit" and "license" attributes.

**Comment by danscholes** [comment]
Hi, I have scheduled a designer and developer for the 10th & 11th June to collate this and then add it to the relevant places in the json files. We'll also provide the details in a Word document so it lives outside of the json file as well.

**Comment by danscholes** [comment]
Image reference added to json for Modules 1-6. We'll provide an updated Word document when image updates are complete containing the info for Modules 7-13.
