### ISSUE TITLE
[All Videos] Need title cards

### ISSUE THREAD

**Issue by davetaz** [theodi/ODI-eLearning#89]
Need place holder pictures (as .png) for each video. 

As we don't have all the videos with intros there will need to be specific place holder pictures produced.

**Comment by danscholes** [comment]
Hi Dave, 

We cant find the parameter name in the component.json to add the image as a placeholder on the video code you have provided, can you please send as an example? The developer looked at the code briefly and it seems like this functionality is not possible without modifying the component. 

Alternatively, we can provide the images to you to input yourself?

Many thanks
Dan

**Comment by danscholes** [comment]
We will send you the the video splash screen images with the videos for you to implement consistently across all.

**Comment by davetaz** [comment]
Hey Dan, I don't suppose that the title cards could include the persons name (from that section of the video) and be taken at a point when their mouth isn't open

**Comment by danscholes** [comment]
Updated images provided via Basecamp 29/06
