### ISSUE TITLE
[Module 2] Narrative 'Cost Savings' text changes

### ISSUE THREAD

**Issue by bcave** [theodi/ODI-eLearning#9]
Capitalise 'Faso' in Burkina Faso.

Pluralise savings in £200 million of savings

Add the following text to the 'in France energy data is being used to' section: 'drive more efficient energy generation practices' with hyperlink: https://www.quandl.com/collections/france/france-energy-data

**Comment by aaronpont** [comment]
Agreed.
Developers,
I have changed the text to accommodate the URL.
Change all text on page 4b - 
![image](https://cloud.githubusercontent.com/assets/12693190/7933746/41133fd6-0919-11e5-8ab9-45c872f67581.png)

**Comment by jasonbutler** [comment]
Text updated - link also added to resources drawer

**Comment by davetaz** [comment]
Fixed by ea58578b9cdbe35a1022cf4d72058363f93ae0dc
